From 713def1d426b959cc98f343ea69ff06db5836dc8 Mon Sep 17 00:00:00 2001
From: Tizio Caio <test@test.com>
Date: Thu, 8 Nov 2018 15:46:06 +0100
Subject: [PATCH] fix: RuntimeError: dictionary changed size during iteration

---
 analyses/cfg/cfg_accurate.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/angr/analyses/cfg/cfg_accurate.py b/analyses/cfg/cfg_accurate.py
index 452b6ac..8cae2ac 100644
--- a/angr/analyses/cfg/cfg_accurate.py
+++ b/angr/analyses/cfg/cfg_accurate.py
@@ -520,7 +520,7 @@ class CFGAccurate(ForwardAnalysis, CFGBase):    # pylint: disable=abstract-metho
                         # will lose some edges in this way, but in general it is acceptable.
                         new_dst.looping_times <= max_loop_unrolling_times):
                     # Log all successors of the dst node
-                    dst_successors = graph_copy.successors(dst)
+                    dst_successors = list(graph_copy.successors(dst))
                     # Add new_dst to the graph
                     edge_data = graph_copy.get_edge_data(src, dst)
                     graph_copy.add_edge(src, new_dst, **edge_data)
-- 
2.7.4

