From 067b462a3a44355bb312db8199ad89223b8872fa Mon Sep 17 00:00:00 2001
From: Emilio Coppa <ercoppa@gmail.com>
Date: Thu, 8 Nov 2018 15:12:51 +0100
Subject: [PATCH] fix: RuntimeError: dictionary changed size during iteration

---
 angr/analyses/cfg/cfg_accurate.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/angr/analyses/cfg/cfg_accurate.py b/angr/analyses/cfg/cfg_accurate.py
index 452b6ac..12179d2 100644
--- a/angr/analyses/cfg/cfg_accurate.py
+++ b/angr/analyses/cfg/cfg_accurate.py
@@ -405,7 +405,7 @@ class CFGAccurate(ForwardAnalysis, CFGBase):    # pylint: disable=abstract-metho
                                 new_dst.looping_times <= max_loop_unrolling_times
                             ):
                             # Log all successors of the dst node
-                            dst_successors = graph.successors(dst)
+                            dst_successors = list(graph.successors(dst))
                             # Add new_dst to the graph
                             edge_data = graph.get_edge_data(src, dst)
                             graph.add_edge(src, new_dst, **edge_data)
-- 
2.7.4

